stages:
  - lint
  - build
  - test
  - cleanup

default:
  image: docker:stable

Dockerfile lint:
  stage: lint
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile

build:
  stage: build
  script:
    - docker build --tag $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .

git test:
  stage: test
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA git --version

black test:
  stage: test
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA black --version

coverage test:
  stage: test
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA coverage --version

isort test:
  stage: test
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA isort --version

pip test:
  stage: test
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA pip3 --version

PyLint test:
  stage: test
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA pylint --version

pytest test:
  stage: test
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA pytest --version

Setuptools test:
  stage: test
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA easy_install-3.7 --version

tox test:
  stage: test
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA tox --version

wheel test:
  stage: test
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA wheel version

cleanup:
  stage: cleanup
  script:
    - docker rmi -f $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
